license="${mod_license}"
issueTrackerURL="https://github.com/Thiov/cave_dweller-neoforge/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Cadentem"
description='''
Fork of the Cave Dweller mod (NeoForge port).
'''

[[mixins]]
config="cave_dweller.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[5.5,)"
    ordering="AFTER"
    side="BOTH"
